Entities/Analisis.cs
using System;
using System.Collections.Generic;

namespace FINNINGWEB.Entities
{
    public partial class Analisis
    {
        public string Id { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public bool? AplicaRca { get; set; }
        public string EventoId { get; set; }
        public string RutPersona { get; set; }
        public bool? Removed { get; set; }

        public virtual Evento Evento { get; set; }
    }
}

Controllers/AnalisisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FINNINGWEB.Models;
using Microsoft.AspNetCore.Identity;
using FINNINGWEB.Entities;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FINNINGWEB.Controllers
{
    [Authorize]
    public class AnalisisController : Controller
    {

        private UserManager<AppUser> userManager;
        public AnalisisController(UserManager<AppUser> userMgr)
        {
            userManager = userMgr;
        }
        private AdventureWorksContext db = new AdventureWorksContext();



        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> CrearFormularioAnalisis(string eventoID)
        {
            AnalisisModels FormularioCrearAnalisis = new AnalisisModels()
            {
                EventoId = eventoID,
                ListaPersonas = db.Persona.ToList(),

            };

            return View(FormularioCrearAnalisis);
        }

        [HttpPost]
        public async Task<IActionResult> CrearFormularioAnalisis(AnalisisModels a)
        {

            if (ModelState.IsValid)
            { 

                Analisis analisis = new Analisis()
            {

                FechaRegistro = a.FechaRegistro,
                AplicaRca = a.AplicaRCA,
                EventoId = a.EventoId,
                Descripcion = a.Descripcion,

                Removed = false,

            };
            db.Analisis.Add(analisis);
            db.SaveChanges();


            if (a.AplicaRCA == false)
            {
                Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == analisis.EventoId);
                updateEvento.Estado = 10;
                updateEvento.Ncaceptada = false;
                db.Evento.Update(updateEvento);
                db.SaveChanges();

            }
            else
            {
                if (a.AplicaRCA == true)
                {
                    Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == analisis.EventoId);
                    updateEvento.Estado = 4;
                    updateEvento.Ncaceptada = null;
                    db.Evento.Update(updateEvento);
                    db.SaveChanges();
                }
            }

                return RedirectToAction("Index", "EventoSecuencia", new { EventoID = a.EventoId });
            }
            else
            {
                return await CrearFormularioAnalisis(a.EventoId.TrimEnd());
            }

    }

        public async Task<IActionResult> EditFormularioAnalisis(string eventoID, string AnalisisID)
        {
            AnalisisModels FormularioCrearAnalisis = new AnalisisModels()
            {
                EventoId = eventoID,
                ListaPersonas = db.Persona.ToList(),
                AnalisisUnico = db.Analisis.FirstOrDefault(c => c.Id == AnalisisID),
                Descripcion = db.Analisis.FirstOrDefault(c => c.Id == AnalisisID).Descripcion,

            };

            return View(FormularioCrearAnalisis);
        }
        [HttpPost]
        public async Task<IActionResult> EditFormularioAnalisis(AnalisisModels analisis)
        {

            if (ModelState.IsValid)
            {
            
            Analisis updateAnalisis = db.Analisis.FirstOrDefault(c => c.Id == analisis.AnalisisUnico.Id);
            updateAnalisis.Descripcion = analisis.Descripcion;
            updateAnalisis.AplicaRca = analisis.AplicaRCA;
            updateAnalisis.FechaRegistro = analisis.FechaRegistro;
            db.Analisis.Update(updateAnalisis);
            db.SaveChanges();

            if (analisis.AplicaRCA == false)
            {
                Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == analisis.EventoId);
                updateEvento.Estado = 10;
                updateEvento.Ncaceptada = false;
                db.Evento.Update(updateEvento);
                db.SaveChanges();
            }
            else
            {
                if (analisis.AplicaRCA == true)
                {
                    Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == analisis.EventoId);
                    updateEvento.Estado = 4;
                    updateEvento.Ncaceptada = null;
                    db.Evento.Update(updateEvento);
                    db.SaveChanges();
                }
            }

                return RedirectToAction("Index", "EventoSecuencia", new { EventoID = analisis.EventoId });
            }
            else
            {
                //string prueba1 = analisis.EventoId.TrimEnd();1
                //string prueba2 = analisis.IdAnalisis;
                return await EditFormularioAnalisis(analisis.EventoId.TrimEnd(),analisis.AnalisisUnico.Id.TrimEnd());
            }
        }

    }
}

Views/Analisis/CrearFormularioAnalisis.cshtml
@model AnalisisModels
<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>REGISTRAR ANALISIS </P>

        </div>
    </div>
    <!--end  Welcome -->
</div>
<form asp-action="CrearFormularioAnalisis" asp-controller="Analisis" class="form-horizontal" role="form" method="post">
    <div class="text-danger" asp-validation-summary="All"></div>   

    <div class="form-group">
        <label class="col-lg-2">EventoId</label>
        <div class="col-lg-3">
            <input class="form-control" asp-for="@Model.EventoId" id="opciones_1" value="@Model.EventoId" readonly="readonly"/>
        </div>
    </div>


    <div class="form-group">
        @*<label  class="col-lg-2 control-label">Fecha Identificacion</label>*@

        @Html.Label("Fecha Registro", null, new { @class = " col-lg-2" })
        <div class="col-lg-3">
            <input class="form-control" asp-for="FechaRegistro" name="FechaRegistro" type="date" required/>
        </div>

    </div>




<div class="form-group">
    <label class="col-lg-2">¿Requiere Analisis Causa Raiz?</label>
    <div class="col-lg-3">
       
        <div class="radio">
            <label>
                <input type="radio" name="AplicaRCA" id="opciones_1" value="true" required>
                SI
            </label>
        </div>
        <div class="radio">
            <label>
                <input type="radio" name="AplicaRCA" id="opciones_2" value="false">
                NO
            </label>
        </div>
    </div>
</div>

<div class="form-group">
    <label class="col-lg-2">Descripción</label>
    <div class="col-lg-5">
        <textarea class="form-control" asp-for="Descripcion" id="textarea" name="Descripcion"
                  placeholder="Descripción"> </textarea>
    </div>
</div>  
        <button type="submit" asp-action="CrearFormularioAnalisis" asp-controller="Analisis" class="btn btn-primary">Registar</button>
        <a asp-action="Index" asp-controller="EventoSecuencia" class="btn btn-default" asp-route-EventoID="@Model.EventoId">Cancelar</a>
</form>

Views/Analisis/EditFormularioAnalisis.cshtml
@model AnalisisModels
@{ 

    string DescripcionTrim;
    if (Model.Descripcion == null)
    {
        DescripcionTrim = null;

    }
    else
    {
        DescripcionTrim = Model.Descripcion.TrimEnd();

    }

    bool Aceptada;
    if (Model.AnalisisUnico.AplicaRca==true)
    {


    }


}


<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>EDITAR ANALSIS </P>

        </div>
    </div>
    <!--end  Welcome -->
</div>
<form asp-action="EditFormularioAnalisis" asp-controller="Analisis" class="form-horizontal" role="form" method="post">
    <div class="text-danger" asp-validation-summary="All"></div>   


    <div class="form-group">
        <label asp-for="@Model.EventoId" class="col-lg-2">Id Evento</label>
        <div class="col-lg-3">
            <input asp-for="@Model.EventoId" class="form-control"
                   placeholder="Id Evento" readonly="readonly">
        </div>
    </div>

    <div class="form-group">
        <label asp-for="@Model.EventoId" class="col-lg-2">Id Analisis</label>
        <div class="col-lg-3">
            <input asp-for="@Model.AnalisisUnico.Id" class="form-control"
                   placeholder="Id Evento" readonly="readonly">
        </div>
    </div>

    @*<div class="form-group">
        <label asp-for="@Model.EventoId" class="col-lg-2">EventoId</label>
        <div class="col-lg-5">
            <input asp-for="@Model.EventoId" id="opciones_1"  readonly="readonly" />
        </div>
    </div>*@

    @if (Model.AnalisisUnico.FechaRegistro != null)
    {
        <div class="form-group">
            @*<label  class="col-lg-2 control-label">Fecha Identificacion</label>*@

            @Html.Label("Fecha Registro", null, new { @class = " col-lg-2" })
            <div class="col-lg-3">
                <input class="form-control" name="FechaRegistro" asp-for="@Model.AnalisisUnico.FechaRegistro" type="date" required />
            </div>

        </div>

    }
    else
    {
        <div class="form-group">
            @*<label  class="col-lg-2 control-label">Fecha Identificacion</label>*@

            @Html.Label("Fecha Registro", null, new { @class = " col-lg-2" })
            <div class="col-lg-3">
                <input class="form-control" name="FechaRegistro"  type="date" required />
            </div>

        </div>

    }

    @if (Model.AnalisisUnico.AplicaRca == true)
    {

        <div class="form-group">
            <label class="col-lg-2">¿Requiere Analisis Causa Raiz?</label>
            <div class="col-lg-3">

                <div class="radio">
                    <label>
                        <input type="radio" checked name="AplicaRCA" id="opciones_1" value="true" required>
                        SI
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="AplicaRCA" id="opciones_2" value="false" required>
                        NO
                    </label>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="form-group">
            <label class="col-lg-2">¿Requiere Analisis Causa Raiz?</label>
            <div class="col-lg-3">

                <div class="radio">
                    <label>
                        <input type="radio" name="AplicaRCA" id="opciones_1" value="true" required>
                        SI
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" checked name="AplicaRCA" id="opciones_2" value="false" required>
                        NO
                    </label>
                </div>
            </div>
        </div>

    }



    <div class="form-group">
        <label class="col-lg-2">Descripción</label>
        <div class="col-lg-5">
            <textarea class="form-control" 
                      placeholder="Descripción"  asp-for="@DescripcionTrim"  name="Descripcion"> </textarea>
        </div>
    </div>
    <div class="text-danger" asp-validation-summary="All"></div>  
    <button type="submit"  class="btn btn-warning">Editar</button>
    <a asp-action="Index" asp-controller="EventoSecuencia" class="btn btn-default" asp-route-EventoID="@Model.EventoId">Cancelar</a>
</form>    