Entities/Evaluacion.cs
using System;
using System.Collections.Generic;

namespace FINNINGWEB.Entities
{
    public partial class Evaluacion
    {
        public string Id { get; set; }
        public string IdEvento { get; set; }
        public bool? Efectiva { get; set; }
        public string Descripcion { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string Estado { get; set; }
        public bool Removed { get; set; }

        public virtual Evento IdEventoNavigation { get; set; }
    }
}

Controllers/EvaluacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FINNINGWEB.Models;
using Microsoft.AspNetCore.Identity;
using FINNINGWEB.Entities;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FINNINGWEB.Controllers
{
    [Authorize]
    public class EvaluacionController : Controller
    {

        private UserManager<AppUser> userManager;
        public EvaluacionController(UserManager<AppUser> userMgr)
        {
            userManager = userMgr;
        }
        private AdventureWorksContext db = new AdventureWorksContext();


        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> FormularioCrearEvaluacion(string eventoID)
        {
            EvaluacionModels em = new EvaluacionModels()
            {
                EventoId = eventoID,
                efectivo = null,

            };
            return View(em);
        }


        [HttpPost]
        public async Task<IActionResult> FormularioCrearEvaluacion(EvaluacionModels em)
        {

            if (ModelState.IsValid)
            {
                Evaluacion e = new Evaluacion()
                {
                    IdEvento = em.EventoId,
                    FechaRegistro = em.FechaRegistro,
                    Efectiva = em.efectivo,
                    Descripcion = em.Descripcion,
                    Removed = false,
                };
                db.Evaluacion.Add(e);
                db.SaveChanges();

                if (em.efectivo != null)
                {
                    if (em.efectivo == true)
                    {

                        Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == em.EventoId);
                        updateEvento.Estado = 9;

                        db.Evento.Update(updateEvento);
                        db.SaveChanges();
                    }
                    else
                    {
                        if (em.efectivo == false)
                        {

                            Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == em.EventoId);
                            updateEvento.Estado = 4;

                            db.Evento.Update(updateEvento);
                            db.SaveChanges();

                        }
                    }

                }






                return RedirectToAction("Index", "EventoSecuencia", new { EventoID = em.EventoId });
            }
            else
            {
                return await FormularioCrearEvaluacion(em.EventoId.TrimEnd());
            }
        }


        public async Task<IActionResult> FormularioEditEvaluacion(string eventoID, string EvaluacionID)
        {
            EvaluacionModels em = new EvaluacionModels()
            {
                EventoId = eventoID,
                ListaPersonas = db.Persona.ToList(),
                 EvaluacionUnica = db.Evaluacion.FirstOrDefault(c => c.Id == EvaluacionID),

            };

            return View(em);
        }

        [HttpPost]
        public async Task<IActionResult> FormularioEditEvaluacion(EvaluacionModels em)
        {

            if (ModelState.IsValid)
            {

                Evaluacion updateEvaluacion = db.Evaluacion.FirstOrDefault(c => c.Id.TrimEnd() == em.EvaluacionUnica.Id);
                updateEvaluacion.FechaRegistro = em.FechaRegistro;
                updateEvaluacion.Efectiva = em.EvaluacionUnica.Efectiva;
                updateEvaluacion.Descripcion = em.Descripcion;
                db.Evaluacion.Update(updateEvaluacion);
                db.SaveChanges();



                if (em.EvaluacionUnica.Efectiva != null)
                {
                    if (em.EvaluacionUnica.Efectiva == true)
                    {

                        Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == em.EventoId);
                        updateEvento.Estado = 9;

                        db.Evento.Update(updateEvento);
                        db.SaveChanges();
                    }
                    else
                    {
                        if (em.EvaluacionUnica.Efectiva == false)
                        {

                            Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == em.EventoId);
                            updateEvento.Estado = 4;

                            db.Evento.Update(updateEvento);
                            db.SaveChanges();

                        }
                    }

                }




                return RedirectToAction("Index", "EventoSecuencia", new { EventoID = em.EventoId.TrimEnd() });
            }
            else
            {
                return await FormularioEditEvaluacion(em.EventoId.TrimEnd(), em.EvaluacionUnica.Id.TrimEnd());
            }
        }


    }
}

Views/Evaluacion/FormularioCrearEvaluacion.cshtml
@model EvaluacionModels
<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>REGISTRAR EVALUACIÓN </P>
        </div>
    </div>

</div>
<form asp-action="FormularioCrearEvaluacion" asp-controller="Evaluacion" class="form-horizontal" role="form" method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group">
        <label class="col-lg-2">EventoId</label>
        <div class="col-lg-3">
            <input class="form-control" asp-for="@Model.EventoId" id="opciones_1" value="@Model.EventoId" readonly="readonly" />
        </div>
    </div>

    <div class="form-group">
        @*<label  class="col-lg-2 control-label">Fecha Identificacion</label>*@
        @Html.Label("Fecha Registro", null, new { @class = " col-lg-2" })
        <div class="col-lg-3">
            <input class="form-control" name="FechaRegistro" type="date" required />
        </div>
    </div>


    <div class="form-group">
        <label class="col-lg-2">¿Analisis Causa Raiz Efectivo?</label>
        <div class="col-lg-3">
            <select asp-for="@Model.efectivo" class="form-control" id="sel2" required>
                <option value="" disabled selected>Selecciona tu opción</option>
                <option value="true">Si</option>
                <option value="false">No</option>

            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2">Descripción</label>
        <div class="col-lg-5">
            <textarea class="form-control" id="textarea" name="Descripcion"
                      placeholder="Descripción"> </textarea>
        </div>
    </div>
    <div class="text-danger" asp-validation-summary="All"></div>
    <button type="submit" asp-action="CrearFormularioAnalisis" asp-controller="Analisis" class="btn btn-primary">Registar</button>
    <a asp-action="Index" asp-controller="EventoSecuencia" class="btn btn-default" asp-route-EventoID="@Model.EventoId">Cancelar</a>
</form> 

Views/Evaluacion/FormularioEditEvaluacion.cshtml
@model EvaluacionModels
@{ 
    string DescripcionVariable = "";
    if (Model.EvaluacionUnica.Descripcion != null)
    {

        DescripcionVariable = Model.EvaluacionUnica.Descripcion.TrimEnd();
    }
}

<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>EDITAR EVALUACIÓN </P>
        </div>
    </div>

</div>
<form asp-action="FormularioEditEvaluacion" asp-controller="Evaluacion" class="form-horizontal" role="form" method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group">
        <label class="col-lg-2">EventoId</label>
        <div class="col-lg-5">
            <input class="form-control" asp-for="@Model.EventoId"  readonly="readonly" />
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-2">Evalaucion Id</label>
        <div class="col-lg-5">
            <input class="form-control" asp-for="@Model.EvaluacionUnica.Id" readonly="readonly" />
        </div>
    </div>

    <div class="form-group">
        @*<label  class="col-lg-2 control-label">Fecha Identificacion</label>*@
        @Html.Label("Fecha Registro", null, new { @class = " col-lg-2" })
        <div class="col-lg-5">
            <input class="form-control" asp-for="@Model.EvaluacionUnica.FechaRegistro" name="FechaRegistro" type="date" required />
        </div>
    </div>

    @if (Model.EvaluacionUnica.Efectiva != null)
    {
       

            <div class="form-group">
                <label class="col-lg-2">¿Analisis Causa Raiz Efectivo?</label>
                <div class="col-lg-5">
                    <select asp-for="@Model.EvaluacionUnica.Efectiva" class="form-control" id="sel2" required>
                        <option value="" disabled selected>Selecciona tu opción</option>
                        <option value="true">Si</option>
                        <option value="false">No</option>

                    </select>
                </div>
            </div>
     

        

        }

    @if (Model.EvaluacionUnica.Descripcion != null)
    {

        <div class="form-group">
            <label class="col-lg-2 ">Descripción</label>
            <div class="col-lg-5">
                <textarea name="Descripcion" class="form-control" asp-for="@DescripcionVariable" id="textarea"
                          placeholder="Descripcion" required> </textarea>
            </div>
        </div>

    }
    else
    {

        <div class="form-group">
            <label class="col-lg-2 ">Descripción</label>
            <div class="col-lg-5">
                <textarea name="Descripcion" class="form-control"
                          placeholder="Descripcion" required> </textarea>
            </div>
        </div>

    }


    <div class="text-danger" asp-validation-summary="All"></div>
    <button type="submit" asp-action="FormularioEditEvaluacion" asp-controller="Evaluacion" class="btn btn-warning">Editar</button>
    <a asp-action="Index" asp-controller="EventoSecuencia" class="btn btn-default" asp-route-EventoID="@Model.EventoId">Cancelar</a>
</form> 