Controllers/DatosController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using FINNINGWEB.Models;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using FINNINGWEB.Entities;
using System.Linq;
using System;
using System.Collections.Generic;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FINNINGWEB.Controllers
{
    [Authorize(Roles = "Admins,Calidad")]
    public class DatosController : Controller
    {
        private UserManager<AppUser> userManager;
        public DatosController(UserManager<AppUser> userMgr)
        {
            userManager = userMgr;
        }

        private AdventureWorksContext db = new AdventureWorksContext();

        [Authorize]
        public IActionResult Index()
        {
            List<Persona> listaJefeArea = new List<Persona>();
            foreach (PersonaArea pa in db.PersonaArea.ToList())
            {
                Persona persona2 = db.Persona.FirstOrDefault(c => c.Rut.TrimEnd().Equals(pa.RutPersona.TrimEnd()));
                listaJefeArea.Add(persona2);
            }

            ListaArea Area = new ListaArea()
            {
                ListaPersonas = listaJefeArea,
                ListaAreas = db.Area.ToList().Where(c=>c.Removed!=true),
                ListaPersonaArea = db.PersonaArea.ToList(),
            };

        


            return View(Area);
        }


        [Authorize]
        public IActionResult IndiceCliente()
        {

            ListaCliente cliente = new ListaCliente()
            {

                ListaClientes = db.Cliente.ToList().Where(c => !c.Removed == true),
            };

            return View(cliente);
        }

        [Authorize]
        public IActionResult IndiceProcesos()
        {

            ListaProceso1 lp = new ListaProceso1()
            {

                ListaProcesos1 = db.Proceso1.ToList(),
            };

            return View(lp);
        }



        public IActionResult FormularioCrearCliente()
        {

            ListaCliente cliente = new ListaCliente()
            {

                ListaClientes = db.Cliente.ToList(),

            };


            return View(cliente);
        }
        [HttpPost]
        public async Task<IActionResult> FormularioCrearCliente(ListaCliente model)
        {

            if (ModelState.IsValid)
            {
                Cliente c = new Cliente()
                {
                    Nombre = model.nombre,
                    Removed = false,

                };
                db.Cliente.Add(c);
                db.SaveChanges();
                return RedirectToAction("IndiceCliente");
            }
            else
            {
                return FormularioCrearCliente();
            }

           
        }



        public IActionResult DeleteCliente(int ClienteId)
        {

            Cliente DeleteCliente = db.Cliente.FirstOrDefault(c => c.Id == ClienteId);
            DeleteCliente.Removed = true;

            db.Cliente.Update(DeleteCliente);
            db.SaveChanges();

            return RedirectToAction("IndiceCliente");

        }

        public IActionResult FormularioEditCliente(int ClienteId)
        {

            ListaCliente lc = new ListaCliente()
            {
                //Id = AreaId,
                //Nombre = db.Area.FirstOrDefault(c => c.Id == AreaId).Nombre,
                //RutJefe = db.Area.FirstOrDefault(c => c.Id == AreaId).RutJefe,
                //ListaPersonas = db.Persona.ToList(),
                ClienteUnico = db.Cliente.FirstOrDefault(c => c.Id == ClienteId),
            };

            return View(lc);
        }

        [HttpPost]
        public async Task<IActionResult> FormularioEditCliente(ListaCliente model)
        {
            if (ModelState.IsValid)
            {
                Cliente updateCliente = db.Cliente.FirstOrDefault(c => c.Id == model.ClienteUnico.Id);
                updateCliente.Nombre = model.nombre;

                db.Cliente.Update(updateCliente);
                db.SaveChanges();

                return RedirectToAction("IndiceCliente");
            }
            else
            {
                return FormularioEditCliente(model.ClienteUnico.Id);
            }
    

        }




        public IActionResult FormularioCrearArea()
        {

            ListaArea Area = new ListaArea()
            {

                //ListaPersonas = db.Persona.ToList(),

            };


            return View(Area);
        }
        [HttpPost]
        public IActionResult FormularioCrearArea(ListaArea model)
        {

            if (ModelState.IsValid)
            {
                Area area = new Area()
                {
                    Nombre = model.NombreArea,
                    //RutJefe = model.RutPersona,
                    //RutJefe = model.AreaUnica.RutJefe
                    Removed = false,
                };
                db.Area.Add(area);
                db.SaveChanges();

                if (model.RutPersona!=null)
                {
                    PersonaArea pa = new PersonaArea()
                    {
                        RutPersona = model.RutPersona.TrimEnd(),
                        IdArea = area.Id,

                    };
                    db.PersonaArea.Add(pa);
                    db.SaveChanges();
                }


               



                //if (db.Persona.FirstOrDefault(c => c.Rut.Equals(model.RutPersona)) != null)
                //{
                //    Persona updatePersona = db.Persona.FirstOrDefault(c => c.Rut.TrimEnd().Equals(model.RutPersona.TrimEnd()));
                //    updatePersona.IdAreaJefeArea = area.Id;
                //    db.Persona.Update(updatePersona);
                //    db.SaveChanges();
                //}
                return RedirectToAction("Index");
            }
            else
            {
                return FormularioCrearArea();
            }

     
        }


        public IActionResult FormularioEditArea(int AreaId)
        {
            string rutJefe = null;
         
            if (db.PersonaArea.FirstOrDefault(c => c.IdArea == AreaId) != null)
            {
                rutJefe = db.PersonaArea.FirstOrDefault(c => c.IdArea == AreaId).RutPersona;
            };

            Area AU = db.Area.FirstOrDefault(c => c.Id == AreaId);
            ListaArea Area1 = new ListaArea()
            {

                AreaUnica = AU,
                RutJefeArea = rutJefe,
                ListaPersonas = db.Persona.ToList(),
                RutPersona = rutJefe,
            };

            string nombrecompleto = null;
            if (rutJefe != null)
            {
                nombrecompleto = db.Persona.Select(c => new { nombreCompleto = c.Nombre.TrimEnd() + " " + c.ApellidoPaterno.TrimEnd() + " " + c.ApellidoMaterno.TrimEnd(), rut = c.Rut }).FirstOrDefault(c => c.rut.TrimEnd().Equals(rutJefe.TrimEnd())).nombreCompleto;
            }
            Area1.NombreCompleto = nombrecompleto;


            return View(Area1);
        }
        [HttpPost]
        public IActionResult FormularioEditArea(ListaArea model)
        {
            if (ModelState.IsValid)
            {
                Area updateArea = db.Area.FirstOrDefault(c => c.Id == model.AreaUnica.Id);
                updateArea.Nombre = model.NombreArea;
                //updateArea.RutJefe = model.AreaUnica.RutJefe;
                db.Area.Update(updateArea);
                db.SaveChanges();

               
                    if (db.PersonaArea.FirstOrDefault(c=> c.IdArea == model.AreaUnica.Id)!=null)
                    {
                        PersonaArea DeletePersonaArea = db.PersonaArea.FirstOrDefault(c => c.IdArea == model.AreaUnica.Id);
                        db.PersonaArea.Remove(DeletePersonaArea);
                        db.SaveChanges();

                        PersonaArea pa = new PersonaArea()
                        {
                            RutPersona = model.RutPersona.TrimEnd(),
                            IdArea = model.AreaUnica.Id

                        };
                        db.PersonaArea.Add(pa);
                        db.SaveChanges();

                    }
                    else
                    {
                    if (model.RutPersona != null)
                    {
                        PersonaArea pa = new PersonaArea()
                        {
                            RutPersona = model.RutPersona.TrimEnd(),
                            IdArea = model.AreaUnica.Id

                        };
                        db.PersonaArea.Add(pa);
                        db.SaveChanges();
                    }
      

                    }

                //if (db.Persona.FirstOrDefault(c => c.Rut.Equals(model.RutPersona)) != null)
                //{
                //    if (db.Persona.FirstOrDefault(c => c.IdAreaJefeArea == model.AreaUnica.Id) != null)
                //    {
                //        Persona updatePersona2 = db.Persona.FirstOrDefault(c => c.IdAreaJefeArea == model.AreaUnica.Id);
                //        updatePersona2.IdAreaJefeArea = null;
                //        db.Persona.Update(updatePersona2);
                //        db.SaveChanges();
                //    }


                //    Persona updatePersona = db.Persona.FirstOrDefault(c => c.Rut.TrimEnd().Equals(model.RutPersona.TrimEnd()));
                //    updatePersona.IdAreaJefeArea = model.AreaUnica.Id;
                //    db.Persona.Update(updatePersona);
                //    db.SaveChanges();
                //}


                return RedirectToAction("Index");
            }
            else
            {
                return FormularioEditArea(model.AreaUnica.Id);
            }


        }
        public ViewResult IndiceSubAreas(int AreaId)
        {
            ListaArea SubArea = new ListaArea()
            {
                //ListaPersonas = db.Persona.ToList(),

Views/Datos/FormularioCrearParte.cshtml
@model CreateParte

<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>CREAR PARTE</P>

        </div>
    </div>
    <!--end  Welcome -->
</div>

@*<div class="bg-primary panel-body"><h4>Create User</h4></div>*@
@*<div asp-validation-summary=" All" class="text-danger "></div>*@
<div>
    <div class="col-lg-10">
        <form asp-action="FormularioCrearParte" class="form-horizontal" method="post">
            <div class="text-danger" asp-validation-summary="All"></div>
            <div class="form-group">
                <label class="col-lg-2 ">Nombre</label>
                <div class="col-lg-3">
                    <input asp-for="Nombre" class="form-control" placeholder="Nombre" required />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 ">Numero Parte</label>
                <div class="col-lg-3">
                    <input asp-for="NumeroParte" class="form-control" placeholder="Numero Parte" />
                </div>
            </div>
       
            <button type="submit" class="btn btn-primary">Crear Parte</button>
            <a asp-action="IndiceParte" asp-controller="Datos" class="btn btn-default">Cancelar</a>
        </form>
    </div>
    <div class="col-lg-2">

    </div>
</div>

Views/Datos/FormularioEditComponente.cshtml
@model ListaComponente



<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>EDITAR COMPONENTE</P>

        </div>
    </div>
    <!--end  Welcome -->
</div>

@*<div class="bg-primary panel-body"><h4>Create User</h4></div>*@
@*<div asp-validation-summary=" All" class="text-danger "></div>*@
<div>
    <div class="col-lg-10">
        <form asp-action="FormularioEditComponente" class="form-horizontal" method="post">

            <div class="form-group">
                <label asp-for="@Model.ComponenteUnico.Id" class="col-lg-2 ">ID</label>
                <div class="col-lg-3">
                    <input asp-for="@Model.ComponenteUnico.Id" class="form-control" placeholder="Nombre"  readonly="readonly" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="@Model.ComponenteUnico.Nombre" class="col-lg-2 ">Nombre</label>
                <div class="col-lg-3">
                    <input asp-for="Nombre" class="form-control" placeholder="Nombre"  required />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="@Model.ComponenteUnico.NumeroSerie" class="col-lg-2 ">Numerio Serie</label>
                <div class="col-lg-3">
                    <input asp-for="NumeroSerie" class="form-control" placeholder="Numerio Serie" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="@Model.ComponenteUnico.Posicion" class="col-lg-2 ">Posición</label>
                <div class="col-lg-3">
                    <input asp-for="Posicion" class="form-control" placeholder="Posición" />
                </div>
            </div>




            <div class="text-danger" asp-validation-summary="All"></div>

            <button type="submit" class="btn btn-warning">Editar</button>
            <a asp-action="PrincipalComponentes" asp-controller="Datos" class="btn btn-default">Cancelar</a>
        </form>
    </div>
    <div class="col-lg-2">

    </div>
</div>

Views/Datos/IndiceCliente.cshtml
@model ListaCliente
@{
    ViewData["Title"] = "Datos Page";


}

<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>CLIENTE</P>

        </div>
    </div>
    <!--end  Welcome -->
</div>
<table class="table table-condensed table-bordered">
    @if (Model.ListaClientes.Count() == 0)
    {
        <tr><td colspan="3" class="text-center"><font color="red">No existen clientes en el sistema!</font></td></tr>
    }
    else
    {
        <tr><th>Id</th><th>Name</th><th>Acción</th></tr>

        foreach (var cliente in Model.ListaClientes)
        {
            <tr>
                <td>@cliente.Id</td>
                <td>@cliente.Nombre</td>
                @*<td>@{ var nombre= from e in Model.ListaPersonas
                    where e.Rut == area.RutJefe
                    select e.Nombre;   } @nombre</td>*@
                @*<td>@Model.ListaPersonas.FirstOrDefault(c=>c.Rut==area.RutJefe).Nombre</td>*@
             


                <td class="text-center">
                    <form asp-action="Delete" method="post">
           
                        <a asp-action="FormularioEditCliente" class="btn btn-sm btn-warning" asp-route-ClienteId="@cliente.Id">Editar</a>
                        @*<a asp-action="DeleteCliente" class="btn btn-danger btn-sm" asp-route-ClienteId="@cliente.Id">
                            Eliminar
                        </a>*@
                        <a onclick="ConfirmarEliminarCliente('@cliente.Id')" class="btn btn-sm  btn-danger">Eliminar</a>
                    </form>
                </td>


            </tr>
        }
    }
</table>
<a class="btn btn-primary" asp-action="FormularioCrearCliente" asp-controller="Datos">Crear Cliente</a>

<script>
    function ConfirmarEliminarCliente(id) {
        confirmar = confirm("¿Esta seguro de eliminar el cliente?");
        if (confirmar) {
            EliminarCliente(id);
        }
    }
</script>
<script>
    function EliminarCliente(id) {
        var action = "DeleteCliente";
        $.ajax({
            type: "POST",
            url: action,
            data: { ClienteId: id },
            success: function (response) {
                location.reload();
            }
        });
    }
</script>

Views/Datos/IndiceComponentes.cshtml
@model ListaModelo


<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>COMPONENTES</P>

        </div>
    </div>
    <!--end  Welcome -->
</div>
<h3>Componentes</h3>
<h5 color="red">Nota: Si desea cambiar los atributos del componente debe ir a la seccion de <a asp-action="PrincipalComponentes"><font color="red">Componente </font>,buscar el componente y editar.   </a></h5>

@*<h3>Componentes del Modelo: @Model.ListaModelos.FirstOrDefault(c=>c.Id==@Model.ModeloId).Nombre</h3>
<h3>Componentes del Equipo: @Model.ListaEquipos.FirstOrDefault(c => c.Id == @Model.EquipoId).Nombre</h3>
<h4>@Model.ModeloId</h4>*@
<table class="table table-condensed table-bordered">
    @if (@Model.ListaModeloComponentes.Where(c => c.IdModelo == @Model.ModeloId).Count() == 0)
    {
        <tr><td colspan="3" class="text-center"><font color="red">No existen componentes del modelo: @Model.ListaModelos.FirstOrDefault(c => c.Id == @Model.ModeloId).Nombre!</font></td></tr>
    }
    else
    {
        <tr><th>Id Modelo Componente</th><th>Equipo</th><th>Modelo</th><th>Componente</th><th>Acción</th></tr>
        @foreach (var modelo in Model.ListaModeloComponentes.Where(c => c.IdModelo == @Model.ModeloId))
        {
            <tr>
                <td>@modelo.Id</td>
                @*<td>@modelo.IdComponente</td>*@
           
                <td>@Model.ListaEquipos.FirstOrDefault(c => c.Id == Model.EquipoId).Nombre</td>
                <td>@Model.ListaModelos.FirstOrDefault(c => c.Id == modelo.IdModelo).Nombre</td>
                <td>@Model.ListaComponentes.FirstOrDefault(c => c.Id == modelo.IdComponente).Nombre</td>

                <td class="text-center">
                    <form asp-action="Delete" method="post">
                        <a asp-action="PrincipalPartes" asp-controller="Datos" class="btn btn-sm btn-primary" asp-route-ComponenteId="@modelo.IdComponente" asp-route-variable="@Model.ModeloId">Partes</a>
                        <a asp-action="FormularioEditModeloComponente" class="btn btn-sm btn-warning" asp-route-ModeloComponenteId="@modelo.Id">Editar ModeloComponente</a>
                        @*<a asp-action="DeleteModeloComponente" class="btn btn-danger btn-sm" asp-route-ModeloComponenteId="@modelo.Id">
                            Eliminar
                        </a>*@
                        <a class="btn btn-sm btn-danger" onclick="ConfirmarEliminarModeloComponente('@modelo.Id')">Eliminar</a>
                    </form>
                </td>


            </tr>
        }

    }
</table>
<a class="btn btn-primary" asp-action="FormularioAsociarComponente" asp-controller="Datos" asp-route-ModeloId="@Model.ModeloId">Asociar Componente</a>
<a class="btn btn-default" asp-action="IndiceModelos" asp-controller="Datos" asp-route-EquipoId="@Model.EquipoId">Cancelar</a>
<script>
    function ConfirmarEliminarModeloComponente(Id) {

        confirmar = confirm("¿Esta seguro de eliminar el Componente?");
        if (confirmar) {
            EliminarModeloComponente(Id);
        }
    }
</script>
<script>

   function EliminarModeloComponente(Id) {
       var action = "DeleteModeloComponente";
       $.ajax({
         type: "POST",
         url: action,
         data: { MOdeloComponenteId: Id },
         success: function (response) {
            location.reload();
              }
         });

        }

</script>

Views/Datos/IndiceEquipos.cshtml
@model ListaEquipo


<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>EQUIPOS</P>

        </div>
    </div>
    <!--end  Welcome -->
</div>

<table class="table table-condensed table-bordered">
    @if (Model.ListaEquipos.Count() == 0)
    {
        <tr><td colspan="3" class="text-center"><font color="red">No existen equipos en el sistema!</font></td></tr>
    }
    else
    {
        <tr><th>Id</th><th>Nombre</th><th>Acción</th></tr>

        foreach (var Equipo in Model.ListaEquipos)
        {
            <tr>
                <td>@Equipo.Id</td>
                <td>@Equipo.Nombre</td>
                
      
                @*<td>@{ var nombre= from e in Model.ListaPersonas
                    where e.Rut == area.RutJefe
                    select e.Nombre;   } @nombre</td>*@
                @*<td>@Model.ListaPersonas.FirstOrDefault(c=>c.Rut==area.RutJefe).Nombre</td>*@
                @*<td>@Model.ListaPersonas.Select(c => new { nombreCompleto = c.Nombre + c.ApellidoPaterno, rut = c.Rut }).FirstOrDefault(c => c.rut == area.RutJefe).nombreCompleto</td>*@


                <td class="text-center">
                    <form asp-action="Delete" method="post">
                        <a asp-action="IndiceModelos" class="btn btn-sm btn-primary" asp-route-EquipoId="@Equipo.Id">Modelos</a>
                        <a asp-action="FormularioEditEquipo" class="btn btn-sm btn-warning" asp-route-EquipoId="@Equipo.Id">Editar</a>
                        @*<a asp-action="DeleteEquipo" class="btn btn-danger btn-sm" asp-route-EquipoId="@Equipo.Id">
                            Eliminar
                        </a>*@
                        <a class="btn btn-sm btn-danger" onclick="ConfirmarEliminarEquipo('@Equipo.Id')">Eliminar</a>
                    </form>
                </td>


            </tr>
        }
    }
</table>
<a class="btn btn-primary" asp-action="FormularioCrearEquipo" asp-controller="Datos" >Crear Equipo</a>

<script>
    function ConfirmarEliminarEquipo(EquipoId) {
      
        confirmar = confirm("¿Esta seguro de eliminar el Equipo?");
        if (confirmar) {
            EliminarEquipo(EquipoId);
        }
    }
</script>
<script>

   function EliminarEquipo(EquipoId) {
       var action = "DeleteEquipo";
       $.ajax({
         type: "POST",
         url: action,
         data: { EquipoId: EquipoId },
         success: function (response) {
            location.reload();
              }
         });

        }

</script>

Views/Datos/IndiceModelos.cshtml
@model ListaModelo


<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>MODELOS</P>

        </div>
    </div>
    <!--end  Welcome -->
</div>  
<h3>Modelos del Equipo: @Model.EquipoUnico.Nombre</h3>
@*<h3>EquipoID: @Model.EquipoId </h3>*@

<table class="table table-condensed table-bordered">
    @if (@Model.ListaModelos.Where(c=>c.IdEquipo==@Model.EquipoId).Count() == 0)
    {
        <tr><td colspan="3" class="text-center"><font color="red">No existen modelos del equipo: @Model.EquipoUnico.Nombre!</font></td></tr>
    }
    else
    {

    
        <tr><th>Id Modelo</th><th>Modelo</th><th>Acción</th></tr>

        @foreach (var modelo in Model.ListaModelos.Where(c => c.IdEquipo == @Model.EquipoId))
        {
            <tr>
                <td>@modelo.Id</td>
                @*<td>@Model.EquipoUnico.Nombre</td>*@
                <td>@modelo.Nombre</td> 

                <td class="text-center">
                    <form asp-action="Delete" method="post">
                        <a asp-action="IndiceComponentes" asp-controller="Datos" class="btn btn-sm btn-primary" asp-route-ModeloId="@modelo.Id">Componentes</a>
                        <a asp-action="FormularioEditModelo" class="btn btn-sm btn-warning" asp-route-ModeloId="@modelo.Id">Editar</a>
                        @*<a asp-action="DeleteModelo" class="btn btn-danger btn-sm" asp-route-ModeloId="@modelo.Id">
                            Eliminar
                        </a>*@
                        <a class="btn btn-sm btn-danger" onclick="ConfirmarEliminarModelo('@modelo.Id')">Eliminar</a>
                    </form>
                </td>


            </tr>
        }
    }
</table>
<a class="btn btn-primary" asp-action="FormularioCrearModelo" asp-controller="Datos" asp-route-EquipoId="@Model.EquipoUnico.Id">Crear Modelo</a>
<a class="btn btn-default" asp-action="IndiceEquipos" asp-controller="Datos" >Cancelar</a>

<script>
    function ConfirmarEliminarModelo(Id) {

        confirmar = confirm("¿Esta seguro de eliminar el Modelo?");
        if (confirmar) {
            EliminarModelo(Id);
        }
    }
</script>
<script>

   function EliminarModelo(Id) {
       var action = "DeleteModelo";
       $.ajax({
         type: "POST",
         url: action,
         data: { MOdeloId: Id },
         success: function (response) {
            location.reload();
              }
         });

        }

</script>

Views/Datos/IndiceParte.cshtml
@model ListaParte


<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>PARTES</P>

        </div>
    </div>
    <!--end  Welcome -->
</div>

<table class="table table-condensed table-bordered">
    @if (Model.ListaPartes.Count() == 0 || Model.ListaPartes.Where(c=>!c.Removed== true).Count()==0 )
    {
      
        <tr><td colspan="3" class="text-center"><font color="red">No existen partes en el sistema!</font></td></tr>
    }
    else
    {
        <tr><th>Id</th><th>Nombre</th><th>NumeroParte</th><th>Acción</th></tr>

        foreach (var parte in Model.ListaPartes.Where(c => !c.Removed == true))
        {
            <tr>
                <td>@parte.Id</td>
                <td>@parte.Nombre</td>
                <td>@parte.NumeroParte</td>



                <td class="text-center">
                    <form asp-action="Delete" method="post">
                      
                        <a asp-action="FormularioEditParte" class="btn btn-sm btn-warning" asp-route-ParteId="@parte.Id">Editar</a>
                        @*<a asp-action="DeleteParte" class="btn btn-danger btn-sm" asp-route-ParteId="@parte.Id">
                            Eliminar
                        </a>*@
                        <a class="btn btn-sm btn-danger" onclick="ConfirmarEliminarParte('@parte.Id')">Eliminar</a>
                    </form>
                </td>


            </tr>
        }
    }
</table>
<a class="btn btn-primary" asp-action="FormularioCrearParte" asp-controller="Datos">Crear Parte</a>
<script>
    function ConfirmarEliminarParte(Id,variable) {

        confirmar = confirm("¿Esta seguro de eliminar la Parte?");
        if (confirmar) {
            EliminarParte(Id);
        }
    }
</script>
<script>

   function EliminarParte(Id) {
       var action = "DeleteParte";
       $.ajax({
         type: "POST",
         url: action,
         data: { ParteId: Id },
         success: function (response) {
            location.reload();
              }
         });

        }

</script>

Views/Datos/PrincipalComponentes.cshtml
@model ListaComponente


<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>COMPONENTES</P>

        </div>
    </div>
    <!--end  Welcome -->
</div>

<table class="table table-condensed table-bordered">
    @if (@Model.ListaComponentes.ToList().Count()==0)
    {
        <tr><td colspan="3" class="text-center"><font color="red">No existen componentes registrados!</font></td></tr>
    }
    else
    {
        <tr><th>Id</th><th>Nombre</th><th>NumeroSerie</th><th>Posicion</th><th>Acción</th></tr>
        @foreach (var Componente in Model.ListaComponentes)
        {
            <tr>
                <td>@Componente.Id</td>
                <td>@Componente.Nombre</td>
                <td>@Componente.NumeroSerie</td>
                <td>@Componente.Posicion</td>




                <td class="text-center">
                    <form asp-action="Delete" method="post">
           
                        <a asp-action="FormularioEditComponente" class="btn btn-sm btn-warning" asp-route-ComponenteId="@Componente.Id">Editar</a>
                        @*<a asp-action="DeleteComponente" class="btn btn-danger btn-sm" asp-route-ComponenteId="@Componente.Id">
                            Eliminar
                        </a>*@
                        <a class="btn btn-sm btn-danger" onclick="ConfirmarEliminarComponente('@Componente.Id')">Eliminar</a>
                    </form>
                </td>





                </tr>
     }
                }
</table>
<a class="btn btn-primary" asp-action="FormularioCreateComponente" asp-controller="Datos">Crear Componente</a>
<a class="btn btn-default" asp-action="Index" asp-controller="Home" >Cancelar</a>
<script>
    function ConfirmarEliminarComponente(Id) {

        confirmar = confirm("¿Esta seguro de eliminar el Componente?");
        if (confirmar) {
            EliminarComponente(Id);
        }
    }
</script>
<script>

   function EliminarComponente(Id) {
       var action = "DeleteComponente";
       $.ajax({
         type: "POST",
         url: action,
         data: { ComponenteId: Id },
         success: function (response) {
            location.reload();
              }
         });

        }

</script>