Entities/Verificacion.cs
using System;
using System.Collections.Generic;

namespace FINNINGWEB.Entities
{
    public partial class Verificacion
    {
        public string Id { get; set; }
        public string IdEvento { get; set; }
        public bool? Efectiva { get; set; }
        public string Descripcion { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string RutPersona { get; set; }
        public string Estado { get; set; }
        public bool Removed { get; set; }

        public virtual Evento IdEventoNavigation { get; set; }
    }
}

Controllers/VerificacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FINNINGWEB.Models;
using Microsoft.AspNetCore.Identity;
using FINNINGWEB.Entities;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FINNINGWEB.Controllers
{

    [Authorize]
    public class VerificacionController : Controller
    {
        private UserManager<AppUser> userManager;
        public VerificacionController(UserManager<AppUser> userMgr)
        {
            userManager = userMgr;
        }
        private AdventureWorksContext db = new AdventureWorksContext();


        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> FormularioCrearVerificacion(string eventoID)
        {
            VerificacionModels vm = new VerificacionModels()
            {
                EventoId = eventoID,
                efectivo = null,

            };
            return View(vm);
        }


        [HttpPost]
        public async Task<IActionResult> FormularioCrearVerificacion(VerificacionModels vm)
        {
            if (ModelState.IsValid)
            {
                Verificacion v = new Verificacion()
                {
                    IdEvento = vm.EventoId,
                    FechaRegistro = vm.FechaRegistro,
                    Efectiva = vm.efectivo,
                    Descripcion = vm.Descripcion,
                    Removed = false,
                };
                db.Verificacion.Add(v);
                db.SaveChanges();



                if (vm.efectivo != null)
                {
                    if (vm.efectivo == true)
                    {

                        Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == vm.EventoId);
                        updateEvento.Estado = 10;

                        db.Evento.Update(updateEvento);
                        db.SaveChanges();
                    }
                    else
                    {
                        //verificar si se debe cerrar el evento o abrir uno nuevo con los mismos datos?
                        if (vm.efectivo == false)
                        {

                            Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == vm.EventoId);
                            updateEvento.Estado = 10;

                            db.Evento.Update(updateEvento);
                            db.SaveChanges();

                        }
                    }

                }



                return RedirectToAction("Index", "EventoSecuencia", new { EventoID = vm.EventoId });
            }
            else
            {


                return await FormularioCrearVerificacion(vm.EventoId.TrimEnd());
            }

        }
        public async Task<IActionResult> FormularioEditVerificacion(string eventoID, string VerificacionID)
        {
            VerificacionModels vm = new VerificacionModels()
            {
                EventoId = eventoID,
                ListaPersonas = db.Persona.ToList(),
                VerificacionUnica = db.Verificacion.FirstOrDefault(c => c.Id == VerificacionID),

            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> FormularioEditVerificacion(VerificacionModels vm)
        {

            if (ModelState.IsValid)
            {
                Verificacion updateVerificacion = db.Verificacion.FirstOrDefault(c => c.Id.TrimEnd() == vm.VerificacionUnica.Id);
                updateVerificacion.FechaRegistro = vm.FechaRegistro;
                updateVerificacion.Efectiva = vm.VerificacionUnica.Efectiva;
                updateVerificacion.Descripcion = vm.Descripcion;
                db.Verificacion.Update(updateVerificacion);
                db.SaveChanges();


                if (vm.VerificacionUnica.Efectiva != null)
                {
                    if (vm.VerificacionUnica.Efectiva == true)
                    {

                        Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == vm.EventoId);
                        updateEvento.Estado = 10;

                        db.Evento.Update(updateEvento);
                        db.SaveChanges();
                    }
                    else
                    {
                        if (vm.VerificacionUnica.Efectiva == false)
                        {
                            //verificar si se debe cerrar el evento o abrir uno nuevo con los mismos datos?
                            Evento updateEvento = db.Evento.FirstOrDefault(c => c.Id == vm.EventoId);
                            updateEvento.Estado = 10;

                            db.Evento.Update(updateEvento);
                            db.SaveChanges();

                        }
                    }

                }

                return RedirectToAction("Index", "EventoSecuencia", new { EventoID = vm.EventoId.TrimEnd() });
            }
            else
            {
                return await FormularioEditVerificacion(vm.EventoId.TrimEnd(), vm.VerificacionUnica.Id.TrimEnd());
            }
        }
    }
}

Views/Verificacion/FormularioCrearVerificacion.cshtml
@model VerificacionModels
<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>REGISTRAR VERIFICACIÓN </P>
        </div>
    </div>

</div>
<form asp-action="FormularioCrearVerificacion" asp-controller="Verificacion" class="form-horizontal" role="form" method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group">
        <label class="col-lg-2">EventoId</label>
        <div class="col-lg-3">
            <input class="form-control" asp-for="@Model.EventoId" id="opciones_1" value="@Model.EventoId" readonly="readonly" />
        </div>
    </div>

    <div class="form-group">
        @*<label  class="col-lg-2 control-label">Fecha Identificacion</label>*@
        @Html.Label("Fecha Registro", null, new { @class = " col-lg-2" })
        <div class="col-lg-3">
            <input class="form-control" name="FechaRegistro" type="date" required />
        </div>
    </div>


    <div class="form-group">
        <label class="col-lg-2">¿Fue Efectivo?</label>
        <div class="col-lg-3">
            <select asp-for="@Model.efectivo" class="form-control" id="sel2" required>
                <option value="" disabled selected>Selecciona tu opción</option>
                <option value="true">Si</option>
                <option value="false">No</option>

            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2">Descripción</label>
        <div class="col-lg-5">
            <textarea class="form-control" id="textarea" name="Descripcion"
                      placeholder="Descripción"> </textarea>
        </div>
    </div>
    <div class="text-danger" asp-validation-summary="All"></div>
    <button type="submit"  class="btn btn-primary">Registar</button>
    <a asp-action="Index" asp-controller="EventoSecuencia" class="btn btn-default" asp-route-EventoID="@Model.EventoId">Cancelar</a>
</form> 

Views/Verificacion/FormularioEditVerificacion.cshtml
@model VerificacionModels
@{
    string DescripcionVariable = "";
    if (Model.VerificacionUnica.Descripcion != null)
    {

        DescripcionVariable = Model.VerificacionUnica.Descripcion.TrimEnd();
    }
}

<div class="row">
    <!-- Welcome -->
    <div class="col-lg-12">
        <div class="alert alert-info">
            <i></i><P>EDITAR VERIFICACION </P>
        </div>
    </div>

</div>
<form asp-action="FormularioEditVerificacion" asp-controller="Verificacion" class="form-horizontal" role="form" method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group">
        <label class="col-lg-2">EventoId</label>
        <div class="col-lg-5">
            <input class="form-control" asp-for="@Model.EventoId" readonly="readonly" />
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-2">Verificacion Id</label>
        <div class="col-lg-5">
            <input class="form-control" asp-for="@Model.VerificacionUnica.Id" readonly="readonly" />
        </div>
    </div>

    <div class="form-group">
        @*<label  class="col-lg-2 control-label">Fecha Identificacion</label>*@
        @Html.Label("Fecha Registro", null, new { @class = " col-lg-2" })
        <div class="col-lg-5">
            <input class="form-control" asp-for="@Model.VerificacionUnica.FechaRegistro" name="FechaRegistro" type="date" required />
        </div>
    </div>

    @if (Model.VerificacionUnica.Efectiva != null)
    {


        <div class="form-group">
            <label class="col-lg-2">¿Fue Efectivo?</label>
            <div class="col-lg-5">
                <select asp-for="@Model.VerificacionUnica.Efectiva" class="form-control" id="sel2" required>
                    <option value="" disabled selected>Selecciona tu opción</option>
                    <option value="true">Si</option>
                    <option value="false">No</option>

                </select>
            </div>
        </div>

    }

    @if (Model.VerificacionUnica.Descripcion != null)
    {

        <div class="form-group">
            <label class="col-lg-2 ">Descripción</label>
            <div class="col-lg-5">
                <textarea name="Descripcion" class="form-control" asp-for="@DescripcionVariable" id="textarea"
                          placeholder="Descripcion" required> </textarea>
            </div>
        </div>

    }
    else
    {

        <div class="form-group">
            <label class="col-lg-2 ">Descripción</label>
            <div class="col-lg-5">
                <textarea name="Descripcion" class="form-control"
                          placeholder="Descripcion" required> </textarea>
            </div>
        </div>

    }


    <div class="text-danger" asp-validation-summary="All"></div>
    <button type="submit" asp-action="FormularioEditVerificacion" asp-controller="Verificacion" class="btn btn-warning">Editar</button>
    <a asp-action="Index" asp-controller="EventoSecuencia" class="btn btn-default" asp-route-EventoID="@Model.EventoId">Cancelar</a>
</form> 